### ISSUE TITLE
非常棒的项目，可是app.vue中为什么要加client only?

### ISSUE THREAD

**Issue by lidongtony** [hdw0504/el-plus-nuxt3#1]
本来就是为了方便seo抓取关键词，所以服务端渲染才用nuxt，加上client only以后使用客户端渲染还能实现这个目的吗？

**Comment by hdw0504** [comment]
[element-plus issue#9414](https://github.com/element-plus/element-plus/issues/9414#issuecomment-1236063757)
[element-plus issue#10797](https://github.com/element-plus/element-plus/issues/10797#issuecomment-1329193633)
这个问题在之前已经有很多人在官方提过问题，但我并没有详细研究过解决方案，大多数都是只是在使用如 `<el-date-picker>` 组件外面加个 `<client-only>`，所以这里我只是在最外层添加为了方便加测试el组件
目前好几个 ui 对 nuxt3 的支持还是不大够，有各种各样的小问题
我把这个问题先记录起来，等后续如果官方有正式的优化完善我再更新

如果你有更好的解决方案可以分享一下~

**Comment by lidongtony** [comment]
了解了，因为ep部分组件的ssr渲染异常，所以使用了条件编译的组件
因为今天刚刚涉及到nuxt3，对这方面不是很了解，感谢您的回复~
建议作者最好写一个demo页面，把部分有问题的ep组件使用条件编译简单展示一下，app.vue中的<client-only />先删掉吧，否则会给starter带来迷惑感。
